trigger:
- main
pool: default

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool: default
    steps:
    - script: echo "Build successful"
- stage: Deploy_Dev
  dependsOn: Build
  jobs:
  - deployment: DeployToDev
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying to DEV environment"
        
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Terraform2(1a39c6ac-4bf8-406a-be20-298e2ae5b5ce)'
              appType: 'webAppLinux'
              appName: 'todoappui'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'
              runtimeStack: 'NODE|24-lts'
